### ISSUE TITLE
生成png链接功能失效

### ISSUE THREAD

**Issue by shanlanCoding** [gkd-kit/inspect#10]
生成zip链接正常，生成png链接转圈后，就没有任何响应了。

**Comment by lisonge** [comment]
我这边实测是可以生成的

你的控制台有什么报错吗？

**Comment by lisonge** [comment]
生成 png 相当于你直接在 issues 底部的文本编辑框里粘贴 png 图片进去，应该是网络问题

你可以在这个这个 issues 的文本编辑框里尝试粘贴一个 png 图片，看看能不能生成链接

**Comment by shanlanCoding** [comment]
粘贴没问题。
![image](https://github.com/gkd-kit/inspect/assets/44717382/dcd686fb-13c8-4265-9ec6-1f1ac7a427b8)

**Comment by lisonge** [comment]
> 你的控制台有什么报错吗？

请给出控制台日志

**Comment by shanlanCoding** [comment]
控制console一切正常

**Comment by shanlanCoding** [comment]
这个图片上传控制台没有网络记录，是不是从油猴子插件上传的？




包括那个zip文件也没有上传网络记录。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月6日(周五) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gkd-kit/inspect] 生成png链接功能失效 (Issue #10)




  
你的控制台有什么报错吗？
  
请给出控制台日志

**Comment by lisonge** [comment]
是的

**Comment by shanlanCoding** [comment]
![image](https://github.com/gkd-kit/inspect/assets/44717382/bed5c6f0-2f77-4360-a692-4aa9015c52b5)

**Comment by shanlanCoding** [comment]
![image](https://github.com/gkd-kit/inspect/assets/44717382/2a6ba4cc-6b13-4973-a704-458c234ff3ad)
````xml
<?xml version="1.0" encoding="UTF-8" ?>
<Error>
	<Code>
		InvalidArgument
	</Code>
	<Message>
		Bucket POST must contain a field named 'key'. If it is specified, please
		check the order of the fields.
	</Message>
	<ArgumentName>
		key
	</ArgumentName>
	<ArgumentValue>
	</ArgumentValue>
	<RequestId>
		BRZ2NX52CCWQAQ4M
	</RequestId>
	<HostId>
		KqxBR2bRPuHJYB6g3KpcejT6tuUtTJaQq9NwN7MG+1P0igJiD1Smf/5wefaprYZGaSPV66aEiLs=
	</HostId>
</Error>
```

**Comment by lisonge** [comment]
这是 Tampermonkey 的 bug  https://github.com/Tampermonkey/tampermonkey/issues/1783

使用 https://violentmonkey.github.io/

**Comment by shanlanCoding** [comment]
![image](https://github.com/gkd-kit/inspect/assets/44717382/11156fdc-962a-44b5-b24f-160be85f6a50)
建议删掉使用这个插件的提示。

**Comment by shanlanCoding** [comment]
这个是检查页面的。

**Comment by lisonge** [comment]
https://github.com/gkd-kit/inspect/commit/c43e78e500c322ad6bf00e454f84f43238ef1986
