### ISSUE TITLE
快照隐私问题

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/inspect#11]
有没有办法考虑允许用户对某些不涉及规则的组件进行类似类似打码或删除的操作。
不然规则书写的时候需要贴上快照，有泄露隐私的风险。

举个例子：
对微信朋友圈广告进行快照的时候，会泄露朋友圈信息。

**Comment by lisonge** [comment]
duplicate

https://github.com/gkd-kit/gkd/issues/16

**Comment by lisonge** [comment]
在新版本发布之前

你可以通过手动解压快照 zip 文件，修改内部的 png，然后重新压缩为 zip

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

**Comment by XFFF2022** [comment]
对于已经上传的带有隐私信息的快照，可以删除或者申请删除吗

**Comment by lisonge** [comment]
你分享快照相当于你在github评论区上传zip，你可以联系 github 删除下面这个链接

```txt
https://github.com/gkd-kit/inspect/files/${github_asset_id}/file.zip
```

其中 `${github_asset_id}` 是你的快照分享出来的 id
