### ISSUE TITLE
网页端快照审查工具打码BUG

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/inspect#13]
GKD 网页端快照审查工具更换域名后原域名的快照图片与文字都回复到原始状态。（已知受影响的是 gkd-kit.songe.li、inspect.gkd.li 转i.gkd.li），而且不是某个特定的快照，而是全部快照都受影响。

举个例子就是打码的图片变成了没打码的，文字替换成***的也显示回了原始文字。
请各位检查一下是否存在隐私泄露问题。

**Comment by lisonge** [comment]
没看懂

**Comment by aoguai** [comment]
> 没看懂

就是原来的快照是打码的，被换成新域名后都没打码了。文字也变回原来的了。

**Comment by lisonge** [comment]
比如呢？请给出一个打码后的快照

**Comment by aoguai** [comment]
> 比如呢？请给出一个打码后的快照 比如呢？ 请给出一个打码后的快照

这个我肯定之前我肯定是已打码了的，现在是未打码状态。别的别人的隐私我也不好举例。
https://i.gkd.li/import/12914450

**Comment by aoguai** [comment]
还有一些别的，我刚开始以为是我记错了是自己没打码，然后渐渐发现怎么都没打码....然后去翻，一翻一个没打码的。

**Comment by lisonge** [comment]
这个链接  <https://i.gkd.li/import/12914450> 表示存储在 github 的一个文件 <https://github.com/gkd-kit/inspect/files/12914450/file.zip>

在你上传生成链接时，这个文件就已经是固定不可更改的，你换哪个域名打开都是完全显示一样的图片，不存在不同域名显示不一致的问题

**Comment by lisonge** [comment]
> 这个我肯定之前我肯定是已打码了的，现在是未打码状态

那它在上传的时候就没有打马赛克，应该是你操作不正确

**Comment by aoguai** [comment]
🤯但是确实是我之前打码的，现在打开就已经是不打码了。那有没有可能是替换图片流程有问题。
我打码是下载快照后在网页端快照审查工具删除快照，用PS打码和替换文本后重新从本地载入快照。
然后在网页端快照审查工具再看一次，确认打码。这过程快照链接始终没变。

**Comment by aoguai** [comment]
这是我刚才发现这情况后，重新打码的一张快照。（之前没换域名前已打码，刚才发现没打码了，又重新打了一边）
![image](https://github.com/gkd-kit/inspect/assets/34203474/5f180ed3-2e70-4ebf-999a-592c08d6e148)
https://i.gkd.li/import/13197443
在我这是显示这样的。

**Comment by lisonge** [comment]
原来你是这种替换，你替换的时候，审查工具没有删除导入链接，然后分享链接的时候就用的原来的没有打码的快照的链接

**Comment by aoguai** [comment]
🤯所以正常替换、分享流程是什么样的

**Comment by lisonge** [comment]
在手机里替换，在手机里上传

**Comment by lisonge** [comment]
我在审查工具加个删除逻辑就行

**Comment by aoguai** [comment]
寄，那我之前的属于是都没打码。

**Comment by aoguai** [comment]
> 在手机里替换，在手机里上传

手机只能替换截图。如果PC替换无效的话，json文件中的文字怎么办。

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/inspect/assets/38517192/c8132437-41a0-4aa8-a4ca-7dd88931a0e6)

**Comment by lisonge** [comment]
> 手机只能替换截图。如果PC替换无效的话，json文件中的文字怎么办。

pc 替换是有效的，你把 id 也改了就行

**Comment by aoguai** [comment]
😥刚开始上传完替换后的压缩文件id也没给我呀，还是用原来的。现在之前替换完的id也拿不到了。

**Comment by lisonge** [comment]
id 是 json 文件里的一个时间戳值，你打开 json 就能看到，或者打开快照预览地址，然后地址栏上链接有一个数字，这个也是 id

**Comment by aoguai** [comment]
😥一开始我还以为是能直接不改变id就能直接替换的，还想着这功能挺好，即便忘记打码了后面发现了改一下也不用怕。现在看来原来是没改成功。
😥现在打码的快照都没了，全是原始没打码的，只能拿到未打码的id。

**Comment by lisonge** [comment]
> 现在打码的快照都没了

它其实还在原来的域名里的，只不过现在那些域名网页不能访问而已

**Comment by aoguai** [comment]
唔...我的意思是我原来打码、分享的流程，导致实际上分享链接的时候就用的原来的没有打码的快照的链接，所以也就只有没打码的快照的id。
另外 如果 id 是 json 文件里的一个时间戳值，那么按我的替换方法的话哪怕换了图片与文字，由于时间戳没改，分享的时候识别到，用的还是原来的id。

**Comment by lisonge** [comment]
> 另外 如果 id 是 json 文件里的一个时间戳值，那么按我的替换方法的话哪怕换了图片与文字，由于时间戳没改，分享的时候识别到，用的还是原来的id。

是的，如果你改 json 的时候，把这个 id 也顺便改了，那就认为是另一个快照

现在加了一个逻辑，导入的时候如果存在分享连接，则自动删除这个分享连接

**Comment by aoguai** [comment]
😭好的。那现在看来，只能慢慢更新规则时候再把原来涉及隐私的链接迭代掉了。

**Comment by lisonge** [comment]
你可以查看你的提交记录，收集所有链接，然后批量修改多个文件提交一个 pr 就行

**Comment by aoguai** [comment]
> 你可以查看你的提交记录，收集所有链接，然后批量修改多个文件提交一个 pr 就行

感觉不太行，第一是修改后原分享链接还能访问，这不就代表免费给别人整理了一份我的隐私😢
第二是检查那边还要手动强拉合并。

**Comment by lisonge** [comment]
行吧，那你可以后续慢慢改
