### ISSUE TITLE
手机浏览器桌面模式下审查工具使用问题

### ISSUE THREAD

**Issue by Mmlss** [gkd-kit/inspect#19]
审查工具无法显示左端图片进行选择控件
![IMG_20240117_131708](https://github.com/gkd-kit/inspect/assets/120915235/411af775-2b4b-4499-8d02-821c62b2d5a7)

**Comment by lisonge** [comment]
无法复现，建议换个浏览器

**Comment by lisonge** [comment]
我是 via_5.0.0 没有复现这个问题

**Comment by lisonge** [comment]
你是不是开启了无图模式，如果开启可以关闭
