### ISSUE TITLE
节点树样式改进

### ISSUE THREAD

**Issue by Sec-ant** [gkd-kit/inspect#2]
直接从这个结构上来看（不进行交互操作的前提下），我会以为 ImageView 是 ViewGroup 的后置兄弟节点，是 LinearLayout 的子节点，但实际上它是 RelativeLayout 的兄弟节点，这个视觉上的误导性有点太强了。

![image](https://github.com/gkd-kit/inspect/assets/10386119/5418eca7-48ed-4323-b0b5-a3787630903b)

**Comment by lisonge** [comment]
请问这个快照链接是什么？

这个 tree 的文档是 <https://www.naiveui.com/zh-CN/os-theme/components/tree>，样式是仿照 android 的 uiautomatorviewer

其实感觉节点前面的数字 childCount 没啥用，可以去掉

**Comment by Sec-ant** [comment]
测试用，没同步到规则里：https://gkd-kit.songe.li/import/12531847

可以用这个选择器定位
```
[id="com.douban.frodo:id/sdk_ad_item"] < RelativeLayout + ImageView
```

> 其实感觉节点前面的数字 childCount 没啥用，可以去掉

支持，或者换成其它显示形式，比如像这样显示在后面：

![image](https://github.com/gkd-kit/inspect/assets/10386119/1abb1a1a-0771-496a-b75c-c9ca30806329)

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/inspect/assets/38517192/7616be94-574e-4270-ae55-7590a341bd6a)

改成这样了，已经部署
