### ISSUE TITLE
华为mate60 pro和Matepad, H OS 4.0, GKD HTTP服务无法被网页端inspect连接

### ISSUE THREAD

**Issue by jenesaispasqui** [gkd-kit/inspect#20]
提示 
接口错误:/device:502
![image](https://github.com/gkd-kit/inspect/assets/156981542/f098bfdd-e1fb-42df-90b3-f603c641c356)

电脑能够ping通 我的手机和平板

请问如何排查其他原因?

谢谢

**Comment by lisonge** [comment]
看起来是代理工具的问题，你把代理工具关掉试试

**Comment by lisonge** [comment]
或者直接在浏览器地址栏打开 <http://192.168.2.43:8888> 如果能打开就能自动连接上

**Comment by jenesaispasqui** [comment]
谢谢! 

的确是我的代理导致的 关了proxy终于连上了 :) 

ps: 直接在浏览器地址栏打开 http://192.168.2.43:8888/ 会直接跳转到https://i.gkd.li/device 感觉更加方便
