### ISSUE TITLE
请问有如何在网页端修改内存订阅?

### ISSUE THREAD

**Issue by jenesaispasqui** [gkd-kit/inspect#21]
有具体的例子或者图例吗? 我现在pr之前 在内存中先测试一下

我翻了一下 没有找到 可能没找对地方 

谢谢

**Comment by lisonge** [comment]
![image](https://github.com/gkd-kit/inspect/assets/38517192/9af61d12-53de-4f73-a0a5-23fffef4d195)

**Comment by jenesaispasqui** [comment]
我的问题是 如何填写这个规则? 是直接将类似 对应app ts中定义的规则 直接放进去? 

![image](https://github.com/gkd-kit/inspect/assets/156981542/227aeb57-09d3-4517-ae85-ab5894e53183)

**Comment by jenesaispasqui** [comment]
终于整明白了

修改内存订阅其实就是定义一个临时的规则集, 单个的类型为 RawApp (xxx\GitHub\subscription\src\types.ts) , 还得静下心来读代码才行 

比如如下: 
{
    id: 'com.tencent.qqlive',
    name: '腾讯视频',
    groups: [ 
	{
            key: 1000,
            name: '去广告开屏',
            activityIds: ['com.tencent.qqlive.ona.activity.SplashHomeActivity'],
            rules: [ 
	       {
                    matches: '[text="跳过"]',
                    action: "longClick",
                    snapshotUrls: 'https://i.gkd.li/snapshot/1705590023836',
                }
            ],
    }, ],
}
