### ISSUE TITLE
[bug] 选择器查询后复制规则有概率丢失exampleUrls字段和snapshotUrls字段

### ISSUE THREAD

**Issue by AIsouler** [gkd-kit/inspect#23]
刷新页面有时恢复正常，有时无效，关闭页面重新打开快照恢复正常

**Comment by lisonge** [comment]
审查工具会在你第一次打开页面时静默生成快照的分享链接，复制出来没有就是静默生成失败

失败就是网络不好，你手动生成就行

**Comment by AIsouler** [comment]
> 审查工具会在你第一次打开页面时静默生成快照的分享链接，复制出来没有就是静默生成失败
> 
> 失败就是网络不好，你手动生成就行

好的，谢谢解答
