### ISSUE TITLE
bug: 快照审查页应用id重复显示

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/inspect#24]
<img width="1280" alt="4d2d0695c95b68ee769d8e92d17041ef" src="https://github.com/gkd-kit/inspect/assets/101449500/46c4d9a1-ca68-4b8a-a823-275fa3eb0999">
如图，微信的应用id应为com.tencent.mm，但是却显示了com.tencent.mmcom.tencent.mm（点击复制出来的应用id正常）

**Comment by lisonge** [comment]
https://github.com/gkd-kit/inspect/commit/d4e8d0a53f8656bf8dbf2ccd66770588728b0db7
