### ISSUE TITLE
bug: 没有quickFind标识，但鼠标悬停时仍提示“可快速查找”

### ISSUE THREAD

**Issue by adproqwq** [gkd-kit/inspect#25]
![image](https://github.com/gkd-kit/inspect/assets/101449500/1e5a52e2-1719-40a3-bfea-34406cbca773)
如题

**Comment by adproqwq** [comment]
> ![image](https://private-user-images.githubusercontent.com/101449500/307492356-1e5a52e2-1719-40a3-bfea-34406cbca773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDcyNDcsIm5iZiI6MTcwODc0Njk0NywicGF0aCI6Ii8xMDE0NDk1MDAvMzA3NDkyMzU2LTFlNWE1MmUyLTE3MTktNDBhMy1iZmVhLTM0NDA2Y2JjYTc3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMzU1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTMzN2E2OTM1MWQyMzI5Zjg5ZjU2MDZhYjEwOWYwZjM0MzcxZmFkNTcyMTk5NjVhMjMwMDUxMzM0NDAyZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mirf2-p20le5ST0BvGr7FRI08-jN9KI0GsK0_bSJXSU) 如题，如果这是网页的刻意设计的话可以关闭

**Comment by lisonge** [comment]
https://github.com/gkd-kit/inspect/commit/37b385f604f955950cf244c727f0f94f303a9d0b
