### ISSUE TITLE
一个没法通过关键字定位的广告

### ISSUE THREAD

**Issue by gaofengwh** [gkd-kit/inspect#29]
之前通关键字定位的方法，自己也写过几条简单的规则，但是下面这个快照没法通过关键字定位，个人能力有限没法定位到关闭广告的控件，怀疑它是计算点击位置的坐标来实现广告关闭，不知道GKD有没有对应的规则。
https://i.gkd.li/i/14719802

**Comment by lisonge** [comment]
https://gkd.li/api/interfaces/RawAppRule.html#position
