### ISSUE TITLE
使用electron等打包为本地应用

### ISSUE THREAD

**Issue by du33169** [gkd-kit/inspect#3]
现在网页连接打开较为麻烦且受网络环境影响，还需要油猴脚本绕过连接，
建议使用electron等打包为本地应用，也方便在无法联网的情况测试规则

**Comment by lisonge** [comment]
另外一个简单的解决方法是你直接 clone 代码然后 `pnpm i` `pnpm serve` 就能运行

当审查工具的 host 是 127.0.0.1/localhost 时，无需油猴脚本也能直接连接手机

后续更新也只需要 `git pull` `pnpm i`

**Comment by lisonge** [comment]
如果你使用 clone ，可以直接使用 gitee 的源

```shell
git clone https://gitee.com/gkd-kit/gkd-kit.git
```

**Comment by lisonge** [comment]
打包为本地应用时，很难更新，还是网页方便，推送代码自动部署自动更新

使用 `https://gitee.com/gkd-kit/gkd-kit.git` 自行在本地启动服务吧
