### ISSUE TITLE
无法生成规则

### ISSUE THREAD

**Issue by Fusuccess** [gkd-kit/inspect#32]
如图所示已经选中了”关闭“的控件，但是不会显示触发规则。第一次使用是不是操作的不对，望指点。
<img width="1664" alt="Snipaste_2024-05-24_18-29-57" src="https://github.com/gkd-kit/inspect/assets/58240731/bfd71414-c58c-42c2-981d-d8b851468640">
https://i.gkd.li/snapshot/1716545231519

**Comment by lisonge** [comment]
我的设备无法看到你的快照链接，你需要手动点击一次你发的快照链接

**Comment by adproqwq** [comment]
不是选择节点程序生成规则，
而是你自己写规则，程序返回符合条件的节点。
你的想法就错了

**Comment by Fusuccess** [comment]
> 不是你选择节点，程序生成规则， 而是你自己写规则，程序返回符合条件的节点。 你的想法就错了

好的，谢谢
