### ISSUE TITLE
微博信息流广告识别不到 [x] 

### ISSUE THREAD

**Issue by oahnaLiew** [gkd-kit/inspect#33]
[快照链接](https://i.gkd.li/i/15747758)

只能识别到一个 ViewGroup，里面的按钮都识别不出。

**Comment by lisonge** [comment]
识别不到，是因为微博提供的节点信息本来就是这样的，你找微博，别找我

如果你想自定义点击位置，可以通过 <https://gkd.li/api/interfaces/RawRuleProps.html#position>
