### ISSUE TITLE
HTTP服务中快照生成链接无反应

### ISSUE THREAD

**Issue by AlcheXie** [gkd-kit/inspect#34]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/faq/)
- [X] 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://f.gkd.li/16076133

### BUG描述(文字/截图/视频)

如题，写一些自定义规则自用，点击“生成链接”后转完圈圈没有任何反应，刷新页面照旧是显示的“生成”而不是“查看”。
上一次这样写规则是3个月前，那时候是成功的。

### 期望行为(文字/截图/视频)

像以前一样，生成过程没问题，完毕弹出地址或提示成功

### 实际行为(文字/截图/视频)

无反应

**Comment by lisonge** [comment]
网页控制台有报错吗

**Comment by lisonge** [comment]
你的脚本管理器是什么

**Comment by jiuqianyuan** [comment]
> 还真是脚本管理器的问题，我之前因为在折腾别的用了beta版的油猴，现在换回去就可以了，谢谢！

你换到了什么版本，我用chrome 130，tampermonkey 5.3.2上传不了，

**Comment by lisonge** [comment]
https://violentmonkey.github.io/
