### ISSUE TITLE
网页审查工具问题

### ISSUE THREAD

**Issue by ice345** [gkd-kit/inspect#35]
![屏幕截图 2024-07-03 165725](https://github.com/gkd-kit/inspect/assets/143070544/00bce943-e384-47b0-84d8-4b4743f10aa7)
![屏幕截图 2024-07-03 165433](https://github.com/gkd-kit/inspect/assets/143070544/a987c808-0f6a-4109-a493-60fcb18bdc64)

**Comment by lisonge** [comment]
你的电脑 和 手机 不在一个局域网下导致的

你把输入框里的地址复制粘贴到浏览器地址栏后回车如果能访问通，会自动跳转连接的
