### ISSUE TITLE
[feat] 选择器查询框宽度支持调整

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/inspect#5]
如图所示，建议选择器查询框的宽度支持调整，对于高分屏，左侧有大片空白，完全可以将查询框拉长一点，以便更好地显示较长的规则。
![image](https://github.com/gkd-kit/inspect/assets/45487685/bcca39ef-8969-4495-be34-d248087c9e80)

**Comment by lisonge** [comment]
感谢建议，后续加上
