### ISSUE TITLE
[bug] 节点过多导致大量节点被丢弃

### ISSUE THREAD

**Issue by Snoopy1866** [gkd-kit/inspect#6]
快照：https://gkd-kit.gitee.io/import/12642514
目标：找到中间的 benner 广告的关闭按钮

Autox.js v6 可以找到按钮，id 为 `banner_item_close`

尝试使用字符搜索 `banner_item_close`，无法找到任何节点，疑似该节点位于 [5001, ]  范围内。

<img width="808" alt="2023-09-17_174305" src="https://github.com/gkd-kit/inspect/assets/45487685/7bef6423-7e78-423c-b214-f6d50989f699">

![95058e487fc1b53acff8506cf7f833e](https://github.com/gkd-kit/inspect/assets/45487685/03bca954-02d6-4a95-b647-8e0e9b8596ec)

**Comment by lisonge** [comment]
是 APP 的 bug <https://github.com/gkd-kit/gkd/issues/28>

**Comment by Snoopy1866** [comment]
尝试手动书写规则 `[id="banner_item_close"]`，在自行选择器中，也无法找到节点。

**Comment by lisonge** [comment]
选择器实时执行是否能直接点击成功？

**Comment by Snoopy1866** [comment]
> 选择器实时执行是否能直接点击成功？

不行

![image](https://github.com/gkd-kit/inspect/assets/45487685/ccb0a4df-d14a-4348-8f19-eeeb5db5a2d2)

**Comment by lisonge** [comment]
选择器写错了，每个 id 前面必定有 appId，可以试试

[id$="banner_item_close"]

**Comment by Snoopy1866** [comment]
Autox.js v6 是可以点完的，应该没有5000个节点，大佬可以看一下 Autox.js 是怎么实现的

**Comment by Snoopy1866** [comment]
> 选择器写错了，每个 id 前面必定有 appId，可以试试
> 
> `[id$="banner_item_close"]`

忘记这茬了，实测 `[id="com.baidu.netdisk:id/banner_item_close"]` 可以点击成功

**Comment by lisonge** [comment]
那个出现大量节点的 bug 的修复 commit 已经提交了，我后续发个版本就行

**Comment by lisonge** [comment]
这个规则可以暂时不用提交快照
