### ISSUE TITLE
特殊输入内容导致“执行选择器”界面出错

### ISSUE THREAD

**Issue by longm21** [gkd-kit/inspect#7]
在如下界面输入了 [text= 之后再输入 ctrl+" 会导致页面失去响应，一段时间后，跳转至”此页存在问题“界面（Edge浏览器），并同时影响同一个浏览器下其他gkd-kit.gitee.io下的页面（都跳转到“此页存在问题”）。
重新试了很多其他的输入内容，有的正常运行，有的出错。
[test=    ->    ctrl+"    ->    出错
[abcd=    ->    ctrl+"    ->    出错
text=    ->    ctrl+"    ->    正常输入
[abc=    ->    ctrl+"    ->    出错
[="     ->光标移到[和=之间    ->    a    ->    出错
用的是油猴
![屏幕截图 2023-09-22 223310](https://github.com/gkd-kit/subscription/assets/145310263/27f701e2-84f0-4c46-83b0-b5eb8cf8cd0b)
![image](https://github.com/gkd-kit/subscription/assets/145310263/54138c33-e3e1-44ef-9565-d6a6c2009648)

**Comment by lisonge** [comment]
不好意思，我用 chrome 和 edge 都尝试了你说的操作，但是没复现

**Comment by lisonge** [comment]
我用的是微软拼音，我换成只能输入英文的美式键盘也是没有复现

**Comment by longm21** [comment]
我换成美式键盘复现了

**Comment by lisonge** [comment]
好的，我复现了，我看看怎么解决[a

**Comment by lisonge** [comment]
先简单在 js 端加了个校验，这个应该是 kotlin parser 那边的错误

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/commit/aa706b9fd58ab7f2c3c5cdbcc028e6c11ba51848

https://github.com/gkd-kit/inspect/commit/0ade427cc1942b75a0faab63ef53eb92945e281d
