### ISSUE TITLE
“选择器查询”查不到树上显示的节点

### ISSUE THREAD

**Issue by longm21** [gkd-kit/inspect#8]
https://gkd-kit.gitee.io/import/12727070
我能用"[text="去开启"] + ImageView"查到结点，用"[text="去开启"] + FrameLayout"却查不到，我应该没有犯语法错误吧？
![屏幕截图 2023-09-26 195540](https://github.com/gkd-kit/inspect/assets/145310263/79cab35e-7d6e-4074-97ed-507db7994e41)

**Comment by lisonge** [comment]
`[text="去开启"] +2 FrameLayout`

**Comment by lisonge** [comment]
> 我应该没有犯语法错误吧？

语法错误 在 编辑器会会直接提示报错的
